version: '3'

services:
  kafka:
    image: landoop/fast-data-dev
    hostname: kafka
    container_name: kafka
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0
      FORWARDLOGS: 0
      SAMPLEDATA: 0
      CONNECT_HEAP: 128M
      CONNECT_PORT: 0
      CONNECTORS:
    ports:
      - 2181:2181
      - 3030:3030
      - 9081-9083:8081-8083
      - 9581-9585:9581-9585
      - 9092:9092
