spring:
  kafka:
    bootstrap-servers: localhost:9092
    request-topic: request-topic
    request-reply-topic: request-reply-topic
    consumer-group: request-reply-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
